name: Pylint
on:
  schedule:
    - cron: '30 10 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
jobs:
  pytest:
    name: Running pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install -r requirements.txt
      - name: Run pylint
        run: |
          pylint --fail-under=7 ./rest_kv
